### ISSUE TITLE
Create new hook_spring

### ISSUE THREAD

**Issue by k00lthing** [k00lkiller/seamans-gear-hackaton#1]
<img width="448" alt="hook_spring_before" src="https://user-images.githubusercontent.com/29853223/194709111-9a528cf3-38fe-4ef0-98cf-860e65df0fbd.png">

**Comment by Dawinartor** [comment]
@Ferb96 finished this issue. 
The object is available as [Spring_Break.glb](https://github.com/k00lkiller/seamans-gear-hackaton/blob/main/Spring_Break.glb)
